### ISSUE TITLE
'ErrorException' with message 'Undefined index: addon.php'

### ISSUE THREAD

**Issue by flakerimi** [anomalylabs/translator-module#3]
I am having this strange error, when I try to translate any plugin:

Path: http://pyro.dev/admin/translator/translate/anomaly.module.configuration
Error: 500
```
[2016-06-30 14:03:40] local.ERROR: exception 'ErrorException' with message 'Undefined index: addon.php' in /Users/flakerimi/Sites/pyrocms/core/anomaly/translator-module/src/Translation/Form/TranslationFormFields.php:62

Stack trace:
#0 /Users/flakerimi/Sites/pyrocms/core/anomaly/translator-module/src/Translation/Form/TranslationFormFields.php(62): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined index...', '/Users/flakerim...', 62, Array)

#1 [internal function]: Anomaly\TranslatorModule\Translation\Form\TranslationFormFields->handle(Object(Anomaly\TranslatorModule\Translation\Form\TranslationFormBuilder), Object(Illuminate\Config\Repository))

#2 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(1187): call_user_func_array(Array, Array)

#3 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(1232): Illuminate\Container\Container->call(Array, Array)

#4 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(1184): Illuminate\Container\Container->callClass('Anomaly\\Transla...', Array, NULL)

#5 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(19531): Illuminate\Container\Container->call('Anomaly\\Transla...', Array)

#6 /Users/flakerimi/Sites/pyrocms/vendor/anomaly/streams-platform/src/Ui/Form/Component/Field/FieldResolver.php(41): Anomaly\Streams\Platform\Support\Resolver->resolve('Anomaly\\Transla...', Array)
#7 /Users/flakerimi/Sites/pyrocms/vendor/anomaly/streams-platform/src/Ui/Form/Component/Field/FieldInput.php(121): Anomaly\Streams\Platform\Ui\Form\Component\Field\FieldResolver->resolve(Object(Anomaly\TranslatorModule\Translation\Form\TranslationFormBuilder))
#8 /Users/flakerimi/Sites/pyrocms/vendor/anomaly/streams-platform/src/Ui/Form/Component/Field/FieldBuilder.php(69): Anomaly\Streams\Platform\Ui\Form\Component\Field\FieldInput->read(Object(Anomaly\TranslatorModule\Translation\Form\TranslationFormBuilder))
#9 /Users/flakerimi/Sites/pyrocms/vendor/anomaly/streams-platform/src/Ui/Form/Component/Field/Command/BuildFields.php(42): Anomaly\Streams\Platform\Ui\Form\Component\Field\FieldBuilder->build(Object(Anomaly\TranslatorModule\Translation\Form\TranslationFormBuilder))
#10 [internal function]: Anomaly\Streams\Platform\Ui\Form\Component\Field\Command\BuildFields->handle(Object(Anomaly\Streams\Platform\Ui\Form\Component\Field\FieldBuilder))
#11 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(1187): call_user_func_array(Array, Array)
#12 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(9472): Illuminate\Container\Container->call(Array)
#13 [internal function]: Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Anomaly\Streams\Platform\Ui\Form\Component\Field\Command\BuildFields))
#14 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(9624): call_user_func(Object(Closure), Object(Anomaly\Streams\Platform\Ui\Form\Component\Field\Command\BuildFields))
#15 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Anomaly\Streams\Platform\Ui\Form\Component\Field\Command\BuildFields))
#16 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(9606): call_user_func(Object(Closure), Object(Anomaly\Streams\Platform\Ui\Form\Component\Field\Command\BuildFields))
#17 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(9479): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#18 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(9465): Illuminate\Bus\Dispatcher->dispatchNow(Object(Anomaly\Streams\Platform\Ui\Form\Component\Field\Command\BuildFields), NULL)
#19 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(5426): Illuminate\Bus\Dispatcher->dispatch(Object(Anomaly\Streams\Platform\Ui\Form\Component\Field\Command\BuildFields))
#20 /Users/flakerimi/Sites/pyrocms/vendor/anomaly/streams-platform/src/Ui/Form/Command/BuildForm.php(77): Anomaly\Streams\Platform\Ui\Form\Command\BuildForm->dispatch(Object(Anomaly\Streams\Platform\Ui\Form\Component\Field\Command\BuildFields))
#21 [internal function]: Anomaly\Streams\Platform\Ui\Form\Command\BuildForm->handle(Object(Illuminate\Events\Dispatcher))
#22 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(1187): call_user_func_array(Array, Array)
#23 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(9472): Illuminate\Container\Container->call(Array)
#24 [internal function]: Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Anomaly\Streams\Platform\Ui\Form\Command\BuildForm))
#25 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(9624): call_user_func(Object(Closure), Object(Anomaly\Streams\Platform\Ui\Form\Command\BuildForm))
#26 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Anomaly\Streams\Platform\Ui\Form\Command\BuildForm))
#27 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(9606): call_user_func(Object(Closure), Object(Anomaly\Streams\Platform\Ui\Form\Command\BuildForm))
#28 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(9479): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#29 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(9465): Illuminate\Bus\Dispatcher->dispatchNow(Object(Anomaly\Streams\Platform\Ui\Form\Command\BuildForm), NULL)
#30 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(5426): Illuminate\Bus\Dispatcher->dispatch(Object(Anomaly\Streams\Platform\Ui\Form\Command\BuildForm))
#31 /Users/flakerimi/Sites/pyrocms/vendor/anomaly/streams-platform/src/Ui/Form/FormBuilder.php(179): Anomaly\Streams\Platform\Ui\Form\FormBuilder->dispatch(Object(Anomaly\Streams\Platform\Ui\Form\Command\BuildForm))
#32 /Users/flakerimi/Sites/pyrocms/vendor/anomaly/streams-platform/src/Ui/Form/FormBuilder.php(194): Anomaly\Streams\Platform\Ui\Form\FormBuilder->build(NULL)
#33 /Users/flakerimi/Sites/pyrocms/vendor/anomaly/streams-platform/src/Ui/Form/FormBuilder.php(265): Anomaly\Streams\Platform\Ui\Form\FormBuilder->make(NULL)
#34 /Users/flakerimi/Sites/pyrocms/core/anomaly/translator-module/src/Http/Controller/Admin/TranslationsController.php(104): Anomaly\Streams\Platform\Ui\Form\FormBuilder->render()
#35 [internal function]: Anomaly\TranslatorModule\Http\Controller\Admin\TranslationsController->translate(Object(Anomaly\TranslatorModule\Translation\Form\TranslationFormBuilder), 'anomaly.module....')
#36 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(8904): call_user_func_array(Array, Array)
#37 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(8973): Illuminate\Routing\Controller->callAction('translate', Array)
#38 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(8953): Illuminate\Routing\ControllerDispatcher->call(Object(Anomaly\TranslatorModule\Http\Controller\Admin\TranslationsController), Object(Illuminate\Routing\Route), 'translate')
#39 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#40 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(9624): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#41 /Users/flakerimi/Sites/pyrocms/vendor/anomaly/streams-platform/src/Http/Middleware/CheckForMaintenanceMode.php(77): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 [internal function]: Anomaly\Streams\Platform\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(9616): call_user_func_array(Array, Array)
#44 /Users/flakerimi/Sites/pyrocms/vendor/barryvdh/laravel-stack-middleware/src/ClosureHttpKernel.php(30): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 /Users/flakerimi/Sites/pyrocms/vendor/symfony/http-kernel/HttpCache/HttpCache.php(487): Barryvdh\StackMiddleware\ClosureHttpKernel->handle(Object(Illuminate\Http\Request), 1, true)
#46 /Users/flakerimi/Sites/pyrocms/vendor/symfony/http-kernel/HttpCache/HttpCache.php(444): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Illuminate\Http\Request), true)
#47 /Users/flakerimi/Sites/pyrocms/vendor/symfony/http-kernel/HttpCache/HttpCache.php(326): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Illuminate\Http\Request), true)
#48 /Users/flakerimi/Sites/pyrocms/vendor/symfony/http-kernel/HttpCache/HttpCache.php(210): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Illuminate\Http\Request), true)
#49 /Users/flakerimi/Sites/pyrocms/vendor/barryvdh/laravel-stack-middleware/src/ClosureMiddleware.php(36): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Illuminate\Http\Request))
#50 [internal function]: Barryvdh\StackMiddleware\ClosureMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#51 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(9616): call_user_func_array(Array, Array)
#52 /Users/flakerimi/Sites/pyrocms/vendor/anomaly/streams-platform/src/Http/Middleware/PoweredBy.php(46): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 [internal function]: Anomaly\Streams\Platform\Http\Middleware\PoweredBy->handle(Object(Illuminate\Http\Request), Object(Closure))
#54 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(9616): call_user_func_array(Array, Array)
#55 /Users/flakerimi/Sites/pyrocms/vendor/anomaly/streams-platform/src/Http/Middleware/SetLocale.php(92): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#56 [internal function]: Anomaly\Streams\Platform\Http\Middleware\SetLocale->handle(Object(Illuminate\Http\Request), Object(Closure))
#57 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(9616): call_user_func_array(Array, Array)
#58 /Users/flakerimi/Sites/pyrocms/vendor/anomaly/streams-platform/src/Http/Middleware/ApplicationReady.php(55): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 [internal function]: Anomaly\Streams\Platform\Http\Middleware\ApplicationReady->handle(Object(Illuminate\Http\Request), Object(Closure))
#60 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(9616): call_user_func_array(Array, Array)
#61 /Users/flakerimi/Sites/pyrocms/vendor/anomaly/streams-platform/src/Http/Middleware/VerifyCsrfToken.php(69): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#62 [internal function]: Anomaly\Streams\Platform\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#63 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(9616): call_user_func_array(Array, Array)
#64 /Users/flakerimi/Sites/pyrocms/core/anomaly/users-module/src/Http/Middleware/AuthorizeRoutePermission.php(102): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#65 [internal function]: Anomaly\UsersModule\Http\Middleware\AuthorizeRoutePermission->handle(Object(Illuminate\Http\Request), Object(Closure))
#66 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(9616): call_user_func_array(Array, Array)
#67 /Users/flakerimi/Sites/pyrocms/core/anomaly/users-module/src/Http/Middleware/AuthorizeControlPanel.php(52): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#68 [internal function]: Anomaly\UsersModule\Http\Middleware\AuthorizeControlPanel->handle(Object(Illuminate\Http\Request), Object(Closure))
#69 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(9616): call_user_func_array(Array, Array)
#70 /Users/flakerimi/Sites/pyrocms/core/anomaly/users-module/src/Http/Middleware/AuthorizeModuleAccess.php(64): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#71 [internal function]: Anomaly\UsersModule\Http\Middleware\AuthorizeModuleAccess->handle(Object(Illuminate\Http\Request), Object(Closure))
#72 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(9616): call_user_func_array(Array, Array)
#73 /Users/flakerimi/Sites/pyrocms/core/anomaly/users-module/src/Http/Middleware/CheckSecurity.php(87): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#74 [internal function]: Anomaly\UsersModule\Http\Middleware\CheckSecurity->handle(Object(Illuminate\Http\Request), Object(Closure))
#75 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(9616): call_user_func_array(Array, Array)
#76 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#77 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(9606): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#78 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(8954): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#79 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(8939): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Anomaly\TranslatorModule\Http\Controller\Admin\TranslationsController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'translate')
#80 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(7888): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Anomaly\\Transla...', 'translate')
#81 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(7859): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#82 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(7512): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#83 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#84 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(9624): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#85 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#86 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(9606): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#87 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(7513): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#88 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(7501): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#89 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(7486): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#90 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(2310): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#91 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#92 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(9624): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#93 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(12975): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#94 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#95 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(9616): call_user_func_array(Array, Array)
#96 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(11567): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#97 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#98 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(9616): call_user_func_array(Array, Array)
#99 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(12712): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#100 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#101 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(9616): call_user_func_array(Array, Array)
#102 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(12649): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#103 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#104 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(9616): call_user_func_array(Array, Array)
#105 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#106 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(9606): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#107 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(2257): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#108 /Users/flakerimi/Sites/pyrocms/bootstrap/cache/compiled.php(2240): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#109 /Users/flakerimi/Sites/pyrocms/public/index.php(57): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#110 {main} 
```

**Comment by RyanThompson** [comment]
Is this still an issue?

**Comment by martijnmegens** [comment]
Yes, but the solution is simple, always keep the default language (en) active, or the
$translation array will be empty.
